version: "3.9"

services:
  postgres:
    image: postgres
    container_name: hackathon_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hackathon_db
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: hackathon_redis
    ports:
      - "6379:6379"